### ISSUE TITLE
Feature: Add configuration support for Interface Breakout

### ISSUE THREAD

**Issue by Exonical** [netascode/terraform-nxos-nac-nxos#8]
Feature: Add configuration support for Interface Breakout

**Description:**
Add the necessary YAML structure and Terraform logic within this module to configure interface breakout on NX-OS devices.

This feature depends on the CiscoDevNet/terraform-provider-nxos provider [adding support ](https://github.com/CiscoDevNet/terraform-provider-nxos/issues/318) for managing interface breakout configurations. An issue has been proposed/created upstream: [Link to the upstream issue you created/will create, if available]

Proposed YAML Structure: We need to define how users will specify breakout configurations in the input YAML files. A potential structure under system or perhaps a dedicated interfaces section could be:

yaml
# Option 1: Under system configuration per device
```yaml
nxos:
  devices:
    - name: Switch1
      configuration:
        system:
          # ... other system settings ...
          interface_breakouts:
            - module: 1
              port: 49
              map: "10g-4x"
            - module: 1
              port: 50
              map: "10g-4x"
```

# Option 2: More tied to interface definitions (if module handles interfaces)
# This might be more complex depending on current module structure
```
nxos:
  devices:
    - name: Switch1
      configuration:
        interfaces:
          physical:
            Eth1/49:
              breakout: "10g-4x"
              # ... other interface settings ...
```
(Decision needed on the best YAML structure based on module design)

Required Module Changes:

Define YAML Schema: Finalize the input structure in variables.tf or documentation.
Update Locals: Add logic (likely in locals.tf) to process the breakout configuration from the input YAML.
Add Terraform Resource: Create resource blocks (e.g., in a new nxos_interface_breakout.tf file?) that utilize the (future) nxos_interface_breakout resource from the upstream provider, feeding it data processed in the locals block.
Add Example: Update example YAML files (examples/*) to demonstrate usage.
